### ISSUE TITLE
Installation JavaScripts

### ISSUE THREAD

**Issue by KuGelFaaaNg** [php-censor/php-censor#152]
## Expected behavior

JavaScripts should be installed in ```/public/assets/vendor/```

## Actual behavior

JavaScripts are installed in ```/vendor```

## Steps to reproduce

Run 
```bash
composer install
composer update
```

## Environment

* Ubuntu 16.04
* PHP 7.2
* Composer version 1.6.3

**Comment by leewillis77** [comment]
I'm just trying out PHP-Censor after a recommendation on the UK Laravel slack channel, but I've been unable to get everything up and running, and I suspect my issue is similar. 

I've installed the app as per the instructions in the README - however all third-party JS *and* CSS are 404-ing. I replaced my standard NGINX config with the one recommended in the docs (which looks like it has PHP handle missing .js/.css files) in case that made a difference, but it doesn't look like it does, I just get the following error on any of the failing .js / .css file URLs

![screenshot 2018-02-21 10 55 43](https://user-images.githubusercontent.com/1097338/36476457-d9ecbe20-16f5-11e8-9532-19ff3f81e952.png)

Let me know if you think there's the same root cause, or if you'd prefer me to open a fresh issue.

Thanks!

**Comment by KuGelFaaaNg** [comment]
I think PHP should not handle the missing files.
These files should be called directly.
The error I suspect in Composer.
So you should be in the right place here and not open a fresh issue.

**Comment by corpsee** [comment]
@KuGelFaaaNg @leewillis77 Thank you for the reports! I will try to fix it soon.

P.S.: @leewillis77 You may try to install version `0.20.0` for now.

**Comment by KuGelFaaaNg** [comment]
@leewillis77 

Try the following commands as a workaround in your main direcory.

```bash
cp -r vendor/npm-asset/sprintf-js public/assets/vendor/
cp -r vendor/npm-asset/codemirror public/assets/vendor/
cp -r vendor/bower-asset/admin-lte public/assets/vendor/
cp -r vendor/bower-asset/font-awesome public/assets/vendor/
cp -r vendor/bower-asset/ionicons public/assets/vendor/
cp -r vendor/bower-asset/raphael public/assets/vendor/
cp -r vendor/bower-asset/eve-raphael public/assets/vendor/
mv public/assets/vendor/ionicons public/assets/vendor/ion-icons
```

**Comment by corpsee** [comment]
@KuGelFaaaNg @leewillis77 Can you test my fix of assets? (Already in `master` branch).

**Comment by leewillis77** [comment]
@corpsee Yep - worksforme :)

**Comment by KuGelFaaaNg** [comment]
@corpsee 

Works for mee, too but you have a misstake in yout paths.

```GET https://domain.tld/assets/vendor/ion-icons/css/ionicons.min.css net::ERR_ABORTED```

I solve this in my commands with `

```bash
mv public/assets/vendor/ionicons public/assets/vendor/ion-icons
```

**Comment by leewillis77** [comment]
ionicons.min.css loads fine for me on a fresh install from master...

**Comment by corpsee** [comment]
@KuGelFaaaNg

**Comment by KuGelFaaaNg** [comment]
Sry I dont think so. You need to rename the folder or to change the paths where you include ion-icons.

````json
"installer-paths": {
      "public/assets/vendor/{$name}/": ["type:bower-asset", "type:npm-asset"]
    }
```

**Comment by corpsee** [comment]
@KuGelFaaaNg :+1: Fixed.

**Comment by KuGelFaaaNg** [comment]
Work's perfect now 👍
